CREATE TABLE IF NOT EXISTS prices(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    brand_id BIGINT NOT NULL,
	start_date TIMESTAMP,
	end_date TIMESTAMP,
	price_list BIGINT,
    product_id BIGINT,
	priority BIGINT,
    price DECIMAL(10,2),
	curr VARCHAR(3)
);